#!/usr/bin/env python
# coding: utf-8

"""Hidden Attribute Rule — observational learning task (stateful contextual rule induction).

Objects have five symbolic attributes:
  - shape:   CIRCLE / SQUARE / TRIANGLE / PENTAGON / STAR
  - color:   RED / BLUE / GREEN / YELLOW / PURPLE
  - size:    TINY / SMALL / MEDIUM / LARGE / HUGE
  - pattern: SOLID / STRIPED / DOTTED / CHECKERED / SPIRAL
  - border:  NONE / THIN / THICK / DASHED / DOUBLE

THE HIDDEN RULE (stateful / contextual):
  A REFERENCE tuple (same five fields) is shown to the solver at the start.
  For each incoming object, count how many positions match the current REFERENCE
  (equality per slot).

  - If the count is EXACTLY 2: label PASS, and the REFERENCE becomes this object.
  - If the count is 0, 1, 3, 4, or 5: label FAIL; the REFERENCE does not change.

The initial REFERENCE is shown in the prompt:
  (CIRCLE, BLUE, MEDIUM, SOLID, THIN)
What is hidden is the *rule* — threshold k=2 and the update-on-PASS mechanic.

WHY THIS IS HARD (human–model asymmetry):
  - People often track a single "reference" or prototype across a sequence;
    the task rewards that habit. Models frequently overfit to static feature
    correlations and miss state that only lives between lines.
  - The same concrete object can PASS once and FAIL later (demos 1 vs 19),
    which eliminates any rule that labels by object identity alone.
  - No arithmetic or numeric computation: only symbolic equality and
    counting matches (small integers from five slots).

SOLUTION UNIQUENESS (operational semantics):
  - Static rules are impossible: identical tuples receive both PASS and FAIL
    at different indices, so no fixed predicate on attributes suffices.
  - Among stateless thresholds on "number of matching slots vs current
    reference," the demos exhibit FAIL with match counts 0, 1, 3, 4, and 5
    relative to the evolving anchor at each step, and PASS only when the
    count is 2. That pins the threshold to exactly 2 (verified at import:
    no other k in 0..5 reproduces the full label sequence under the same
    update-on-PASS semantics).
  - Under "PASS iff exactly k matches, and only PASS updates the anchor," the
    first PASS forces the next anchor to be that object; any initial anchor
    that makes object 1 a PASS (exactly two slots match object 1) yields the
    same entire demo sequence and the same final anchor. So the literal
    initial anchor is not unique, but the procedure and all labels (and test
    keys) are: there is no second threshold or second update policy that
    fits every example and agrees with the intended tests.

LOGICAL CONSISTENCY:
  - Labels are generated by simulation; module load recomputes them and
    asserts agreement. A solver who recovers the procedure gets a unique
    extension on the held-out objects; no guessing among equally good
    thresholds remains once the demo sequence is fixed.

NOVELTY / ANTI-CONTAMINATION:
  - The trajectory, objects, and distractors are hand-designed for this
    benchmark (not a named puzzle import). The general "hidden state +
    Hamming-like gate" pattern exists in CS pedagogy, but the specific
    sequence, traps, and test set are original.

ANCHOR EVOLUTION (ground truth for the reference initial anchor):
  anchor_0 = (CIRCLE, BLUE, MEDIUM, SOLID, THIN)                    [authoring]
  demo  1 PASS → anchor_1 = (SQUARE, RED, LARGE, SOLID, THIN)
  demo  8 PASS → anchor_2 = (SQUARE, BLUE, MEDIUM, DOTTED, THIN)
  demo 16 PASS → anchor_3 = (STAR, GREEN, LARGE, DOTTED, THIN)
  demo 18 PASS → anchor_4 = (SQUARE, RED, LARGE, SOLID, THIN)       [same as anchor_1]
  demo 26 PASS → anchor_5 = (PENTAGON, PURPLE, LARGE, CHECKERED, THIN)
  demo 32 PASS → anchor_6 = (PENTAGON, YELLOW, MEDIUM, CHECKERED, THICK) [final]

TRAPS IN DEMOS AND TESTS:
  - Early PASSes include BLUE-heavy objects; demo 16 PASS has GREEN (breaks
    color-as-rule).
  - Identical-to-anchor tuples are always FAIL (e.g. demos 6, 13, 19, 31, 37).
  - Test Q2 is identical to the final anchor → FAIL; Q7 has four matches → FAIL.
"""

from dataclasses import dataclass
from itertools import product

import kaggle_benchmarks as kbench


def _log_trace(task, description, prompt, test_results, score, reasoning=""):
    sep = "=" * 70
    print(f"\n{sep}\n  {task}\n{sep}")
    print(f"\n  TASK: {description}")
    print(f"\n  PROMPT:\n{prompt}")
    if reasoning:
        print(f"\n  REASONING:\n{reasoning}")
    print(f"\n  TEST RESULTS:")
    for r in test_results:
        status = "PASS" if r["correct"] else "FAIL"
        print(f"    [{status}] Q{r['q']}: expected={r['expected']!r}  got={r['got']!r}")
    print(f"\n  SCORE: {score:.4f}")
    print(f"{sep}\n")


_TASK_DESCRIPTION = (
    "Objects with five symbolic attributes are labeled PASS/FAIL by a hidden stateful "
    "rule. Labeled examples are provided; the rule involves a hidden internal state "
    "that evolves over time based on the labels. Solve 8 test cases including traps "
    "designed to catch common mis-generalizations."
)

# ── Attribute domains ─────────────────────────────────────────────────────
_SHAPES   = ("CIRCLE", "SQUARE", "TRIANGLE", "PENTAGON", "STAR")
_COLORS   = ("RED", "BLUE", "GREEN", "YELLOW", "PURPLE")
_SIZES    = ("TINY", "SMALL", "MEDIUM", "LARGE", "HUGE")
_PATTERNS = ("SOLID", "STRIPED", "DOTTED", "CHECKERED", "SPIRAL")
_BORDERS  = ("NONE", "THIN", "THICK", "DASHED", "DOUBLE")

_INITIAL_ANCHOR = ("CIRCLE", "BLUE", "MEDIUM", "SOLID", "THIN")


def _count_matches(obj, anchor):
    return sum(o == a for o, a in zip(obj, anchor))


def _apply_rule(sequence, initial_anchor=_INITIAL_ANCHOR):
    """Stateful anchor rule: PASS iff exactly 2 attribute matches; PASS updates anchor."""
    anchor = list(initial_anchor)
    labels = []
    for obj in sequence:
        if _count_matches(obj, anchor) == 2:
            labels.append("PASS")
            anchor = list(obj)
        else:
            labels.append("FAIL")
    return labels, tuple(anchor)


def _labels_with_threshold_k(sequence, k, initial_anchor):
    """Same update semantics as _apply_rule, but PASS iff match count equals k (for uniqueness checks)."""
    anchor = list(initial_anchor)
    labels = []
    for obj in sequence:
        if _count_matches(obj, anchor) == k:
            labels.append("PASS")
            anchor = list(obj)
        else:
            labels.append("FAIL")
    return labels


def _labels_fixed_anchor_no_updates(sequence, initial_anchor):
    """PASS iff k=2 vs initial anchor only; anchor never moves (rules out static-reference shortcuts)."""
    anchor = list(initial_anchor)
    return ["PASS" if _count_matches(obj, anchor) == 2 else "FAIL" for obj in sequence]


# ── Demo objects (shape, color, size, pattern, border) ────────────────────
#
# anchor_0 = (CIRCLE, BLUE, MEDIUM, SOLID, THIN)
#
# Demo  1: SOLID+THIN=2 vs anchor_0 → PASS → anchor_1=(SQUARE,RED,LARGE,SOLID,THIN)
# Demos 2–7: FAILs vs anchor_1 covering match counts 0,1,3,4,5 and a false-positive trap
#
# Demo  8: SQUARE+THIN=2 vs anchor_1 → PASS → anchor_2=(SQUARE,BLUE,MEDIUM,DOTTED,THIN)
# Demos 9–15: FAILs vs anchor_2 covering match counts 0,1,3,4,5
#
# Demo 16: DOTTED+THIN=2 vs anchor_2 (non-BLUE!) → PASS → anchor_3=(STAR,GREEN,LARGE,DOTTED,THIN)
# Demo 17: vs anchor_3 → FAIL: 1 match (GREEN)
# Demo 18: LARGE+THIN=2 vs anchor_3 → PASS → anchor_4=(SQUARE,RED,LARGE,SOLID,THIN) [=anchor_1]
# Demo 19: SAME object as demo 18/1, now 5 matches vs anchor_4 → FAIL [TRAP]
# Demos 20–25: FAILs vs anchor_4 covering match counts 0,1,3,4
#
# Demo 26: LARGE+THIN=2 vs anchor_4 → PASS → anchor_5=(PENTAGON,PURPLE,LARGE,CHECKERED,THIN)
# Demos 27–31: FAILs vs anchor_5 covering match counts 0,1,3,4,5
#
# Demo 32: PENTAGON+CHECKERED=2 vs anchor_5 → PASS → anchor_6=(PENTAGON,YELLOW,MEDIUM,CHECKERED,THICK) [final]
# Demos 33–38: FAILs vs anchor_6 covering match counts 0,1,3,4,5

_DEMO_OBJECTS = [
    # ── vs anchor_0 = (CIRCLE, BLUE, MEDIUM, SOLID, THIN) ──────────────────
    ("SQUARE",   "RED",    "LARGE",     "SOLID",     "THIN"),    #  1 PASS: SOLID+THIN=2       → anchor_1
    # ── vs anchor_1 = (SQUARE, RED, LARGE, SOLID, THIN) ────────────────────
    ("CIRCLE",   "BLUE",   "TINY",      "DOTTED",    "DOUBLE"),  #  2 FAIL: 0 matches
    ("CIRCLE",   "RED",    "MEDIUM",    "STRIPED",   "DASHED"),  #  3 FAIL: 1 (RED)
    ("TRIANGLE", "RED",    "LARGE",     "SOLID",     "DASHED"),  #  4 FAIL: 3 (RED+LARGE+SOLID)
    ("TRIANGLE", "RED",    "LARGE",     "SOLID",     "THIN"),    #  5 FAIL: 4 (RED+LARGE+SOLID+THIN)
    ("SQUARE",   "RED",    "LARGE",     "SOLID",     "THIN"),    #  6 FAIL: 5 (identical to anchor_1!) [TRAP]
    ("PENTAGON", "GREEN",  "HUGE",      "SPIRAL",    "NONE"),    #  7 FAIL: 0 matches
    # ── vs anchor_1 = (SQUARE, RED, LARGE, SOLID, THIN) ────────────────────
    ("SQUARE",   "BLUE",   "MEDIUM",    "DOTTED",    "THIN"),    #  8 PASS: SQUARE+THIN=2      → anchor_2
    # ── vs anchor_2 = (SQUARE, BLUE, MEDIUM, DOTTED, THIN) ─────────────────
    ("TRIANGLE", "RED",    "HUGE",      "CHECKERED", "DOUBLE"),  #  9 FAIL: 0 matches
    ("CIRCLE",   "BLUE",   "LARGE",     "SOLID",     "THICK"),   # 10 FAIL: 1 (BLUE)
    ("SQUARE",   "GREEN",  "MEDIUM",    "SPIRAL",    "THIN"),    # 11 FAIL: 3 (SQUARE+MEDIUM+THIN)
    ("SQUARE",   "BLUE",   "MEDIUM",    "SPIRAL",    "THIN"),    # 12 FAIL: 4 (SQUARE+BLUE+MEDIUM+THIN)
    ("SQUARE",   "BLUE",   "MEDIUM",    "DOTTED",    "THIN"),    # 13 FAIL: 5 (identical to anchor_2!) [TRAP]
    ("PENTAGON", "PURPLE", "HUGE",      "SOLID",     "NONE"),    # 14 FAIL: 0 matches
    ("TRIANGLE", "BLUE",   "TINY",      "SPIRAL",    "DASHED"),  # 15 FAIL: 1 (BLUE)
    # ── vs anchor_2 = (SQUARE, BLUE, MEDIUM, DOTTED, THIN) ─────────────────
    ("STAR",     "GREEN",  "LARGE",     "DOTTED",    "THIN"),    # 16 PASS: DOTTED+THIN=2 (non-BLUE!) → anchor_3
    # ── vs anchor_3 = (STAR, GREEN, LARGE, DOTTED, THIN) ───────────────────
    ("CIRCLE",   "BLUE",   "MEDIUM",    "SOLID",     "DOUBLE"),  # 17 FAIL: 0 matches
    # ── vs anchor_3 = (STAR, GREEN, LARGE, DOTTED, THIN) ───────────────────
    ("SQUARE",   "RED",    "LARGE",     "SOLID",     "THIN"),    # 18 PASS: LARGE+THIN=2 (same obj as #1!) → anchor_4
    # ── vs anchor_4 = (SQUARE, RED, LARGE, SOLID, THIN) [same as anchor_1] ─
    ("SQUARE",   "RED",    "LARGE",     "SOLID",     "THIN"),    # 19 FAIL: 5 matches (identical) [TRAP: same obj just PASSed]
    ("CIRCLE",   "BLUE",   "TINY",      "DOTTED",    "DOUBLE"),  # 20 FAIL: 0 matches (same as #2)
    ("STAR",     "RED",    "MEDIUM",    "DOTTED",    "DASHED"),  # 21 FAIL: 1 (RED)
    ("PENTAGON", "RED",    "LARGE",     "SOLID",     "DASHED"),  # 22 FAIL: 3 (RED+LARGE+SOLID)
    ("TRIANGLE", "RED",    "LARGE",     "SOLID",     "THIN"),    # 23 FAIL: 4 (RED+LARGE+SOLID+THIN) [same as #5]
    ("CIRCLE",   "GREEN",  "HUGE",      "SPIRAL",    "DOUBLE"),  # 24 FAIL: 0 matches
    ("PENTAGON", "BLUE",   "TINY",      "SPIRAL",    "DOUBLE"),  # 25 FAIL: 0 matches
    # ── vs anchor_4 = (SQUARE, RED, LARGE, SOLID, THIN) ────────────────────
    ("PENTAGON", "PURPLE", "LARGE",     "CHECKERED", "THIN"),    # 26 PASS: LARGE+THIN=2       → anchor_5
    # ── vs anchor_5 = (PENTAGON, PURPLE, LARGE, CHECKERED, THIN) ───────────
    ("CIRCLE",   "BLUE",   "SMALL",     "DOTTED",    "DOUBLE"),  # 27 FAIL: 0 matches
    ("STAR",     "RED",    "SMALL",     "SOLID",     "THIN"),    # 28 FAIL: 1 (THIN)
    ("PENTAGON", "RED",    "LARGE",     "SPIRAL",    "THIN"),    # 29 FAIL: 3 (PENTAGON+LARGE+THIN)
    ("PENTAGON", "PURPLE", "LARGE",     "SPIRAL",    "THIN"),    # 30 FAIL: 4 (PENTAGON+PURPLE+LARGE+THIN)
    ("PENTAGON", "PURPLE", "LARGE",     "CHECKERED", "THIN"),    # 31 FAIL: 5 (identical to anchor_5!) [TRAP]
    # ── vs anchor_5 = (PENTAGON, PURPLE, LARGE, CHECKERED, THIN) ───────────
    ("PENTAGON", "YELLOW", "MEDIUM",    "CHECKERED", "THICK"),   # 32 PASS: PENTAGON+CHECKERED=2 → anchor_6
    # ── vs anchor_6 = (PENTAGON, YELLOW, MEDIUM, CHECKERED, THICK) [final] ─
    ("STAR",     "RED",    "LARGE",     "SOLID",     "THIN"),    # 33 FAIL: 0 matches
    ("CIRCLE",   "YELLOW", "HUGE",      "SPIRAL",    "DASHED"),  # 34 FAIL: 1 (YELLOW)
    ("PENTAGON", "YELLOW", "MEDIUM",    "SPIRAL",    "THICK"),   # 35 FAIL: 4 (PENTAGON+YELLOW+MEDIUM+THICK)
    ("PENTAGON", "YELLOW", "MEDIUM",    "CHECKERED", "DOUBLE"),  # 36 FAIL: 4 (PENTAGON+YELLOW+MEDIUM+CHECKERED)
    ("PENTAGON", "YELLOW", "MEDIUM",    "CHECKERED", "THICK"),   # 37 FAIL: 5 (identical to anchor_6!) [TRAP]
    ("TRIANGLE", "PURPLE", "HUGE",      "SOLID",     "NONE"),    # 38 FAIL: 0 matches
]

_VERIFIED_LABELS, _FINAL_ANCHOR = _apply_rule(_DEMO_OBJECTS)

# ── Test cases (against final anchor_6=(PENTAGON,YELLOW,MEDIUM,CHECKERED,THICK)) ──
#
# Q1: (STAR,BLUE,LARGE,CHECKERED,THICK) — CHECKERED+THICK=2 → PASS
# Q2: (PENTAGON,YELLOW,MEDIUM,CHECKERED,THICK) — 5 matches (identical) → FAIL [TRAP]
# Q3: (PENTAGON,YELLOW,MEDIUM,DOTTED,DASHED) — PENTAGON+YELLOW+MEDIUM=3 → FAIL [TRAP]
# Q4: (CIRCLE,RED,LARGE,SOLID,THICK) — THICK=1 → FAIL
# Q5: (CIRCLE,YELLOW,MEDIUM,SOLID,NONE) — YELLOW+MEDIUM=2 → PASS
# Q6: (CIRCLE,RED,TINY,CHECKERED,THICK) — CHECKERED+THICK=2 → PASS
# Q7: (PENTAGON,YELLOW,MEDIUM,CHECKERED,NONE) — PENTAGON+YELLOW+MEDIUM+CHECKERED=4 → FAIL [TRAP]
# Q8: (TRIANGLE,GREEN,SMALL,SPIRAL,DASHED) — 0 matches → FAIL

_RAW_TEST = [
    ("STAR",     "BLUE",   "LARGE",  "CHECKERED", "THICK"),
    ("PENTAGON", "YELLOW", "MEDIUM", "CHECKERED", "THICK"),
    ("PENTAGON", "YELLOW", "MEDIUM", "DOTTED",    "DASHED"),
    ("CIRCLE",   "RED",    "LARGE",  "SOLID",     "THICK"),
    ("CIRCLE",   "YELLOW", "MEDIUM", "SOLID",     "NONE"),
    ("CIRCLE",   "RED",    "TINY",   "CHECKERED", "THICK"),
    ("PENTAGON", "YELLOW", "MEDIUM", "CHECKERED", "NONE"),
    ("TRIANGLE", "GREEN",  "SMALL",  "SPIRAL",    "DASHED"),
]

_TEST_CASES = [
    (*obj, ("PASS" if _count_matches(obj, _FINAL_ANCHOR) == 2 else "FAIL"))
    for obj in _RAW_TEST
]


def _verify_task_integrity():
    """Import-time checks: demo/rule alignment, unique threshold k=2, anchor invariance."""
    recomputed, final_official = _apply_rule(_DEMO_OBJECTS)
    if recomputed != _VERIFIED_LABELS:
        raise AssertionError("demo labels do not match _apply_rule(_DEMO_OBJECTS)")

    for k in range(6):
        if k == 2:
            continue
        if _labels_with_threshold_k(_DEMO_OBJECTS, k, _INITIAL_ANCHOR) == _VERIFIED_LABELS:
            raise AssertionError(f"demo sequence is also consistent with match threshold k={k}")

    if _labels_fixed_anchor_no_updates(_DEMO_OBJECTS, _INITIAL_ANCHOR) == _VERIFIED_LABELS:
        raise AssertionError("demos fit a fixed anchor without updates — stateful rule not forced")

    o1 = _DEMO_OBJECTS[0]
    domains = (_SHAPES, _COLORS, _SIZES, _PATTERNS, _BORDERS)
    for A0 in product(*domains):
        if _count_matches(A0, o1) != 2:
            continue
        lab, fin = _apply_rule(_DEMO_OBJECTS, initial_anchor=A0)
        if lab != _VERIFIED_LABELS or fin != final_official:
            raise AssertionError(
                "labels or final anchor depend on initial anchor beyond the first-object PASS class"
            )

    for obj in _RAW_TEST:
        expected = "PASS" if _count_matches(obj, _FINAL_ANCHOR) == 2 else "FAIL"
        row = next(t for t in _TEST_CASES if t[:5] == obj)
        if row[-1] != expected:
            raise AssertionError(f"test row {obj} expected {expected}, got {row[-1]}")


_verify_task_integrity()


# ── Prompt builder ────────────────────────────────────────────────────────
def _fmt_obj(shape, color, size, pattern, border):
    return (
        f"shape={shape}, color={color}, size={size}, "
        f"pattern={pattern}, border={border}"
    )


def _build_prompt(demo_objects, demo_labels, test_cases):
    lines = [
        "You are studying a hidden classification rule.",
        "Each object has five attributes: shape, color, size, pattern, border.",
        "Objects are classified PASS or FAIL. A special object called the REFERENCE",
        "is also maintained; it is shown at the start and may change over time.",
        "",
        f"  REFERENCE: {_fmt_obj(*_INITIAL_ANCHOR)}",
        "",
        "Observations:",
    ]
    for i, (obj, label) in enumerate(zip(demo_objects, demo_labels), 1):
        lines.append(f"  {i:2d}. {_fmt_obj(*obj)} → {label}")
    lines.append("")
    lines.append("Now classify these 8 new objects:")
    for i, (*attrs, _) in enumerate(test_cases, 1):
        lines.append(f"  Q{i}: {_fmt_obj(*attrs)} → ?")
    return "\n".join(lines)


def _prepare():
    prompt = _build_prompt(_DEMO_OBJECTS, _VERIFIED_LABELS, _TEST_CASES)

    def grade_fn(response):
        results = []
        correct = 0
        for i, (*_, expected) in enumerate(_TEST_CASES, 1):
            raw = getattr(response, f"answer_{i}", None)
            got = str(raw).strip().upper() if raw is not None else ""
            ok = got == expected
            if ok:
                correct += 1
            results.append({"q": i, "expected": expected, "got": got, "correct": ok})
        return correct / len(_TEST_CASES), results

    return prompt, grade_fn


@dataclass
class _Answer:
    answer_1: str
    answer_2: str
    answer_3: str
    answer_4: str
    answer_5: str
    answer_6: str
    answer_7: str
    answer_8: str


@kbench.task(
    name="hidden_attribute_rule_obs_learning",
    description=(
        "Five symbolic attributes per object; PASS/FAIL from a hidden anchor that moves "
        "only on PASS when exactly two slots match. Examples pin k=2 and forbid static "
        "predicates (same tuple, different labels). Tests the final anchor only."
    ),
)
def hidden_attribute_rule_obs_learning(llm) -> float:
    """Infer a stateful contextual PASS/FAIL rule from labeled examples; classify 8 objects."""
    prompt, grade_fn = _prepare()
    try:
        response = llm.prompt(prompt, schema=_Answer)
    except Exception:
        response = None

    if response is not None:
        score, test_results = grade_fn(response)
    else:
        score = 0.0
        test_results = [
            {"q": i, "expected": _TEST_CASES[i - 1][-1], "got": None, "correct": False}
            for i in range(1, len(_TEST_CASES) + 1)
        ]

    reasoning = (
        getattr(response, "reasoning", "") or getattr(response, "thinking", "") or ""
    )
    _log_trace(
        task="hidden_attribute_rule_obs_learning",
        description=_TASK_DESCRIPTION,
        prompt=prompt,
        test_results=test_results,
        score=score,
        reasoning=str(reasoning),
    )
    return score


if __name__ == "__main__":
    hidden_attribute_rule_obs_learning.run(kbench.llm)

